name: Go

on:
  # pull_request:
  #   branches: ["main"]
  # push:
  #   branches: ["main"]
  workflow_dispatch: {}

jobs:
  # unit:
  #   runs-on: [self-hosted]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22'
  #     - run: make test
  # integration:
  #   runs-on: [self-hosted]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22'
  #     - run: make integration
